[project]
name = "llm-code-review"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "llm>=0.25",
    "pyinstaller>=6.13.0",
    "rich>=14.0.0",
]
